App11/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

handler404= 'App11.views.custom_page_not_found'

urlpatterns = [
    path("",include("blog.urls")),
    path('admin/', admin.site.urls)
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns=[
        path("", views.index, name="index"),
        path("post/<str:slug>", views.news, name="News"),
        path("new_something", views.new_url_view, name="newUrlPage"),
        path("old_url", views.old_url_redirect, name="old_url"),
        path("about", views.about_view, name="about"),
        path("register", views.register, name="register"),
        path("login", views.login, name="login"),
        path("dashboard", views.dashboard, name="dashboard"),
        path("logout", views.logout, name="logout"),
        path("forgot_password", views.forgot_password, name="forgot_password"),
        path("reset_password/<uidb64>/<token>", views.reset_password, name="reset_password"),
        path("new_post", views.new_post, name="new_post"),
        path("edit_post/<int:post_id>", views.edit_post, name="edit_post"),
        path("delete_post/<int:post_id>", views.delete_post, name="delete_post")
]

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

# Category
class Category(models.Model):
    name = models.CharField(max_length=100)

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    img_url = models.ImageField(null=True, upload_to="posts/images",blank=True )
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, blank=True)  # Allow blank slugs initially
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user= models.ForeignKey(User,on_delete=models.CASCADE,null=True)

    def save(self, *args, **kwargs):
        if not self.slug:  # Prevent overwriting existing slugs
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    @property
    def formatted_img_url(self):
        if self.img_url:
            try:
                return self.img_url.url
            except:
                pass
        return "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg"
    

    def __str__(self):
        return self.title

class AboutUs(models.Model):
    content = models.TextField()

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

from blog.models import Category, Post

class RegisterForm(forms.ModelForm):
    username=forms.CharField(label="username",max_length=100,required=True)
    email=forms.CharField(label="email",max_length=100,required=True)
    password=forms.CharField(label="password",max_length=100,required=True)
    password_confirm=forms.CharField(label="confirm password",max_length=100,required=True)


    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    def clean(self):
        cleaned_data=super().clean()
        password=cleaned_data.get("password")
        password_confirm=cleaned_data.get("password_confirm")

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError("Password Doesn't Match")
        
class LoginForm(forms.Form):
    username=forms.CharField(label="username",max_length=100,required=True)
    password=forms.CharField(label="password",max_length=100,required=True)

    def clean(self):
        cleaned_data=super().clean()
        username=cleaned_data.get("username")
        password=cleaned_data.get("password")

        if username and password:
            user=authenticate(username=username,password=password)
            if user is None:
                raise forms.ValidationError("Invalid Username and Password")


class ForgotPasswordForm(forms.Form):
    email=forms.EmailField(label="email",max_length=150,required=True)

    def clean(self):
        cleaned_data=super().clean()
        email=cleaned_data.get('email')

        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email Doesn't Exist")

class ResetPasswordForm(forms.Form):
    new_password=forms.CharField(label="password",min_length=8,required=True)
    confirm_password=forms.CharField(label="confirm password",min_length=8,required=True)

    def clean(self):
        cleaned_data=super().clean()
        new_password=cleaned_data.get("new_password")
        confirm_password=cleaned_data.get("confirm_password")

        if new_password and confirm_password and new_password != confirm_password:
            raise forms.ValidationError("Password Doesn't Match")


class PostForm(forms.ModelForm):
    title = forms.CharField(label="title", max_length=100, required=True)
    content = forms.CharField(label="content", max_length=1000, required=True)
    category = forms.ModelChoiceField(label="category",  required=True, queryset=Category.objects.all())
    img_url=forms.ImageField(label='Image',required=False)


    class Meta:
        model = Post
        fields = ['title', 'content', 'category','img_url']
    
    def clean(self):
        cleaned_data=super().clean()
        title=cleaned_data.get("title")
        content=cleaned_data.get("content")

        if title and len(title)<5:
            raise forms.ValidationError("Title should be at least 5 characters long")
    
        if content and len(content)<10:
            raise forms.ValidationError("Content should be at least 10 characters long")
    

    def save(self, commit = ...):
        post=super().save(commit)
        cleaned_data=super().clean()

        if cleaned_data.get('img_url'):
            post.img_url=cleaned_data.get('img_url')
        else:
            img_url="https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg"
            post.img_url=img_url
        
        if commit:
            post.save()
        return post

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from django.urls import reverse
from .models import Category, Post,AboutUs  # Ensure the model is named `Post` with a capital P
from django.core.paginator import Paginator
from .forms import  LoginForm, PostForm, RegisterForm,ForgotPasswordForm, ResetPasswordForm
from django.contrib import messages
from django.contrib.auth import authenticate,login as auth_login,logout as auth_logout
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode

from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import send_mail 
from django.contrib.auth.decorators import login_required,permission_required
from django.contrib.auth.models import Group

def index(request):
    blog_title = "New Post"
    
    all_posts = Post.objects.all() 

    #pagination
    paginator= Paginator(all_posts,5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

     # Fetch all posts from the database
    return render(request, 'index.html', {"blog_title": blog_title, 'page_obj': page_obj})

def news(request, slug):

    if request.user and not request.user.has_perm('blog.view_post'):
        messages.error(request,"You have no Permission to view any post")
        return redirect('blog:index')
    
    try:
        post_obj = Post.objects.get(slug=slug) 

        related_posts=Post.objects.filter(category=post_obj.category).exclude(pk=post_obj.id)
    
    except Post.DoesNotExist:

        raise Http404("Post does not exist")
    return render(request, 'detail.html', {'post': post_obj,'related_posts':related_posts})  # Updated variable name

def old_url_redirect(request):
    return redirect(reverse('blog:newUrlPage'))

def new_url_view(request):
    return HttpResponse("Hello, you are in the New Section")



def about_view(request):
    about_content=AboutUs.objects.first()
    if about_content is None or not about_content.content:
        about_content="Default content here"
    else:
        about_content=about_content.content
    return render(request,'about.html',{"about_content":about_content})


def register(request):
    form=RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            #set reader_group
            readers_group,created=Group.objects.get_or_create(name="Readers")
            user.groups.add(readers_group)
            messages.success(request,"You Registered Successfully!")
            return redirect("blog:login")
        
    return render(request,'register.html',{'form':form})

def login(request):
    form=LoginForm()
    if request.method == 'POST':
        form=LoginForm(request.POST)
        if form.is_valid():
            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            user=authenticate(username=username, password=password)
            if user is not None:
                auth_login(request,user)
                print("Login Success")
                return redirect("blog:dashboard")
           

            #print("Login Success")
    return render(request,'login.html',{'form':form})



def dashboard(request):
    blog_title="My Post"
    all_posts=Post.objects.filter(user=request.user)

    paginator= Paginator(all_posts,5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request,'dashboard.html',{'blog_title':blog_title,'page_obj':page_obj})


def logout(request):
    auth_logout(request)
    return redirect("blog:index")


def forgot_password(request):
    form=ForgotPasswordForm()
    if request.method=='POST':
        form=ForgotPasswordForm(request.POST)
        if form.is_valid():
            email=form.cleaned_data['email']
            user= User.objects.get(email=email)
            token= default_token_generator.make_token(user)

            uid=urlsafe_base64_encode(force_bytes(user.pk))

            current_site =get_current_site(request)
        
            domain=current_site.domain
            
            subject="Reset Password Requested"
        
            message=render_to_string('reset_password_email.html',{
                'domain':domain,
                'uid':uid,
                'token':token,
            })

            send_mail(subject,message,'noreplay@example.com',[email])
            messages.success(request,"Email has been  sent ")


    return render(request,'forgot_password.html',{'form':form})



def reset_password(request,uidb64,token):
    form=ResetPasswordForm()
    if request.method=='POST':
        form=ResetPasswordForm(request.POST)
        if form.is_valid():
            new_password=form.cleaned_data['new_password']
            try:
           
                uid=urlsafe_base64_decode(uidb64)
                user=User.objects.get(pk=uid)
            except(TypeError,ValueError,OverflowError,User.DoesNotExist):
                user=None
            if user is not None and default_token_generator.check_token(user,token):
                user.set_password(new_password)
                user.save()
                messages.success(request,"Password has been changed")
                return redirect('blog:login')
            else:
                messages.error(request,'The Password Reset link is invalid')

        

    return render(request,'reset_password.html',{'form':form})

@login_required
@permission_required('blog.add_post',raise_exception=True)
def new_post(request):
    
    categories=Category.objects.all()
    form=PostForm()
    if request.method=='POST':
       form=PostForm(request.POST,request.FILES)
       if form.is_valid():
           post=form.save(commit=False)
           post.user=request.user
           post.save()
           return redirect('blog:dashboard')
            

    return render(request,'new_post.html',{'categories':categories,'form':form})


@login_required
def edit_post(request,post_id):
    categories=Category.objects.all()
    post=get_object_or_404(Post, id=post_id)
    form=PostForm()
    if request.method=='POST':
       form=PostForm(request.POST,request.FILES, instance=post)
       if form.is_valid():
           form.save()
           return redirect('blog:dashboard')
    return render(request,'edit_post.html',{'categories':categories,'post':post,'form':form})


@login_required
def delete_post(request,post_id):
    post=get_object_or_404(Post, id=post_id)
    post.delete()
    
    return redirect('blog:dashboard')
    


'''
 user=form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
'''

'''

            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            user=authenticate(username=username, password=password)
            if user is not None:
                auth_login(request,user)
                print("Login Success")
                 return redirect("/dashboard")

'''

blog/templates/about.html
{% extends 'base.html ' %}



{%block content%}

    
    <div class="container-fluid ">
        <h3>About Us</h3>
        <div class="d-flex gap-3 justify-content-center mt-5">
            <img src="https://picsum.photos/300/300" alt="">
            <div class="content">

                {{about_content}}
                
            </div>
            
        </div>
    </div>
{% endblock%}  

blog/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body >
   
  
    <!-- Header content.-->

    {% include 'includes/header.html' %}
    
    <!-- Dynamic content.-->

            {%block content%}

            
            {%endblock%}
    
    <!-- Footer content.-->
    {% include 'includes/footer.html' %}

   

   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/dashboard.html
{% extends 'base.html ' %}



{%block content%}
    <div class="container-fluid ">
        <div class="row">
          <div class="col-6">
              <h3> Hi, {{user.username}} </h3>
          </div>
          <div class="col d-flex justify-content-end">
              <div>
                  <h2>Your Groups:</h2>
                  <ul>
                    {% for group in user.groups.all %}
                      <li>{{group.name}}</li>
                    {% empty %}
                      <li>You are not a member of any groups.</li>
                    {% endfor %}
                  </ul>
              </div>
          </div>
        </div>
        <div class="row d-flex justify-content-center">
          <div class="col-6">
              
          </div>
        </div>
        <div class="row">
          <h2 class="mt-3">{{blog_title}}</h2>
          {% if perms.blog.add_post %}
          <div class="d-flex justify-content-center">
              <a href="{% url 'blog:new_post' %}" class="btn btn-success">New Post</a>
          </div>
          {% endif %}
        </div>
        <div class="row m-3">
            {% if page_obj %}
            {% for post in page_obj %}
               <div class="col-4  mb-4">
               <div class="card">
                   <div class="card-body">
                       <div class="row">
                           <div class="col-md-4">
                               <img style="height:300; width:300;" src="{{post.formatted_img_url}}" class="img-fluid" alt="...">
                           </div>
                           <div class="col-md-8">
                               <h5 class="card-title">{{post.title}}</h5>
                               <p class="card-text">{{post.content}}</p>
                               <div class="d-flex justify-content-between">
                                    <a href="/post/{{post.slug}}">Read More</a>
                                   <a class="text-decoration-none text-dark fw-bold" href="#">{{post.category.name}}</a>
                               </div>
                               <div class="d-flex justify-content-between mt-2">
                                <a class="btn btn-warning btn-sm" href="{% url 'blog:edit_post' post.id %}">Edit Post</a>
                                <button class="btn btn-danger btn-sm" onclick="confirmBeforeDelete(`{% url 'blog:delete_post' post.id %}`)">Delete Post</button>
                           
                            </div>
                           </div>
                       </div>
                   </div>
               </div>
               </div>
            {% endfor %}


            <div class="col-12 my-3">

               {%if page_obj.has_other_pages %}

               <nav aria-label="Page navigation">
                   <ul class="pagination">

                       {% if page_obj.has_previous %}
                       <li class="page-item">
                           <a class="page-link" href="?page=1" aria-label="First">
                               <span aria-hidden="true">&laquo; first</span>
                           </a>
                       </li>
                       <li class="page-item">
                           <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                               <span aria-hidden="true">previous</span>
                           </a>
                       </li>
                       {% endif %}


                       <li class="page-item"><span class="page-link">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}.</span></li>

                       <li class="page-item">
                           <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                               <span aria-hidden="true">next</span>
                           </a>
                       </li>
                       <li class="page-item">
                           <a class="page-link" href="?page={{page_obj.paginator.num_pages}}" aria-label="Last">
                               <span aria-hidden="true">last &raquo;</span>
                           </a>
                       </li>
                   </ul>
               </nav>
               {% endif %}    
           </div>
       {% else %}
               <p> There is no Post Yet ! </p>
        {% endif %}
    
                </div>
            </div>

        </div>
      </div>
      <script>
            function confirmBeforeDelete(url)
            {
                var userConfirmed=confirm("Are You sure want to Delete?")

                if(userConfirmed)
                {
                    window.location.href=url
                }
            }
      </script> 
{% endblock%}  
      

blog/templates/detail.html
{%extends 'base.html'%}
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body >
    
    {% block content %}
      
   
    
    <div class="container-fluid ">
       
        <div class="row">
            <div class="col-lg-8">
              <h1 class="mb-4">{{post.title}} <small style="font-size:15px">({{post.category.name}})</small></h1>
              <p class="text-muted">Posted on {{post.created_at| date:"F j Y"}}</p>
              <img src="{{post.formatted_img_url}}" class="img-fluid mb-4" alt="Blog Image">
              <p>{{post.content}}</p>              
            </div>
            <div class="col-lg-4">
              <div class="card mt-3">
                <div class="card-body">
                  <h5 class="card-title">Related Posts</h5>
                  <ul class="list-unstyled">

                    {% for related_post in related_posts %}
                    <li><a href="/post/{{related_post.slug}}">{{related_post.title}}</a></li>
                    {% endfor %}

                  </ul>
                </div>
              </div>
            </div>
        </div>
    </div>

    {% endblock%}
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/edit_post.html
{% extends 'base.html ' %}



{%block content%}

    <div class="container-fluid">
        <div class="row d-flex justify-content-center mt-5">
            <div class="col-4">
                <h3>Edit Post</h3>
                <div class="">
                    {% include 'includes/errors.html' %}
                </div>
    
                <div class="my-3">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="title" class="form-label">Title</label>
                            <input type="text" class="form-control" name="title" id="title" value="{{post.title}}">
                        </div>
                       
                        <div class="form-group">
                            <label for="content" class="form-label">Content</label>
                            <textarea class="form-control" id="content" name="content">{{post.content}}</textarea>
                        </div>

                        <div class="form-group">
                            <label for="image" class="form-label">Image</label>
                            <input type="file" class="form-control-file" name="img_url" id="image">
                        </div>
    
                        <div class="form-group">
                            <label for="category" class="form-label">Category</label>
                            <select class="form-control" id="category" name="category">
                                <option value="">Select</option>
                                {% if categories %}
                                    {% for category in categories%}
                                        <option {% if post.category.id == category.id %}selected {% endif %} value="{{category.id}}">{{category.name}}</option>
                                    {% endfor %}
                                {% endif %}
                                    </select>
                        </div>
                       
                        <div class="my-3 d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
{% endblock%}    
    

blog/templates/forgot_password.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="row d-flex justify-content-center">
            <div class="col-3 mt-3">
                <h2>Forgot Password</h2>
                <div>
                    {% include 'includes/errors.html' %}
                </div>
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="email" class="form-label">Email address</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Send Password Reset Email</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/index.html
{% extends 'base.html ' %}



{%block content%}

    <div class="container-fluid ">
        <div class="row my-2">
            <div class="col">
                <h2 >{{blog_title| upper}} </h2>
            </div>
            <div class="col-3">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search..." aria-label="Search">
                    <button class="btn btn-outline-light btn-primary " type="button" id="button-search">
                      <i class="bi bi-search"></i> <!-- Bootstrap Icons -->
                    </button>
                  </div>
            </div>
        </div>
        <div class="row m-3">
        {% include 'includes/errors.html' %}
        {% if page_obj %}
             {% for post in page_obj %}
                <div class="col-4  mb-4">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <img style="height:300; width:300;" src="{{post.img_url}}" class="img-fluid" alt="...">
                            </div>
                            <div class="col-md-8">
                                <h5 class="card-title">{{post.title}}</h5>
                                <p class="card-text">{{post.content}}</p>
                                <div class="d-flex justify-content-between">
                                     <a href="/post/{{post.slug}}">Read More</a>
                                    <a class="text-decoration-none text-dark fw-bold" href="#">{{post.category.name}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
             {% endfor %}


             <div class="col-12 my-3">

                {%if page_obj.has_other_pages %}

                <nav aria-label="Page navigation">
                    <ul class="pagination">

                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="First">
                                <span aria-hidden="true">&laquo; first</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                                <span aria-hidden="true">previous</span>
                            </a>
                        </li>
                        {% endif %}


                        <li class="page-item"><span class="page-link">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}.</span></li>

                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                                <span aria-hidden="true">next</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.paginator.num_pages}}" aria-label="Last">
                                <span aria-hidden="true">last &raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                {% endif %}    
            </div>
        {% else %}
                <p> There is no Post Yet ! </p>
         {% endif %}
     
     
           
        </div>
        
    </div>
    
{% endblock%}    

blog/templates/login.html
{% extends 'base.html ' %}



{%block content%}

    <div class="container-fluid">
        <div class="row d-flex justify-content-center mt-5">
            <div class="col-4">
                <h3>Login</h3>
                <div class="">
                    
                    {% include 'includes/errors.html' %}
                
                </div>

              

                
    
    
        
                <div class="my-3">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" class="form-control" id="username" name="username" value="{{form.username.value|default:''}}">
                        </div>
                       
                        <div class="form-group">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password">
                        </div>
                       
                        <div class="my-3 d-flex justify-content-between">
                            <a href="{% url 'blog:forgot_password' %}">Forgot Password</a>
                            <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
{% endblock%}  

blog/templates/reset_password_email.html
{% autoescape off %}
    
Hello !

You requested a password reset for your account at {{ domain }}.

Please click the link below to reset your password:

http://{{ domain }}{% url 'blog:reset_password' uidb64=uid token=token %}

Thank You !

{% endautoescape %}